# Generated by Django 4.2 on 2023-06-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upcoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=100)),
                ('release', models.CharField(max_length=100)),
                ('Rating', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('Duration', models.IntegerField(default=True)),
            ],
        ),
    ]
