# Generated by Django 4.2 on 2023-06-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0002_alter_upcoming_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='newmovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=100)),
                ('release', models.CharField(max_length=100)),
                ('Rating', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('Duration', models.IntegerField()),
            ],
        ),
    ]
