# Generated by Django 4.2 on 2023-06-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0004_moviedetailpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmovies',
            name='Duration',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newmovies',
            name='Rating',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
