# Generated by Django 4.2 on 2023-06-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0008_topseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetailpage',
            name='episodes',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='moviedetailpage',
            name='seasons',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
    ]
