# Generated by Django 4.2 on 2023-06-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0010_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='topseries',
            name='video',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
