# Generated by Django 4.2 on 2023-06-24 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0013_topanimes'),
    ]

    operations = [
        migrations.CreateModel(
            name='postcomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('usercomments', models.TextField(max_length=2000)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='websiteapp.moviedetailpage')),
            ],
        ),
    ]
