# Generated by Django 4.2 on 2023-07-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0019_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
