# Generated by Django 4.2 on 2023-07-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0020_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetailpage',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
