# Generated by Django 4.2 on 2023-07-03 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websiteapp', '0021_moviedetailpage_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetailpage',
            name='rating',
        ),
        migrations.CreateModel(
            name='userrating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ratingpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratingpost', to='websiteapp.moviedetailpage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
