# Generated by Django 4.2 on 2023-07-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0026_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customuser',
        ),
    ]
