# Generated by Django 4.2 on 2023-08-01 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0030_alter_movierating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefavorite',
            name='movie_poster',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
