# Generated by Django 4.2 on 2023-05-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='regi',
        ),
    ]
